### ISSUE TITLE
XmlMapper:fromXml fails when input is empty container

### ISSUE THREAD

**Issue by Caspern** [drahak/Restful#48]
When input is empty container like ```<root></root>```, simplexml_load_string returns empty SimpleXMLElement which leads to [this](https://github.com/drahak/Restful/blob/8e1b4aea8cac6a1ebc4de96c764423d1c73b84c0/src/Drahak/Restful/Mapping/XmlMapper.php#L119) exception, but variable ```$error``` is FALSE.

**Comment by drahak** [comment]
Fixed. Thank you.
