### ISSUE TITLE
Custom error codes

### ISSUE THREAD

**Issue by pavoleichler** [drahak/Restful#51]
When displaying errors to clients, the current format is:
```javascript
{
    "code": 404,
    "status": "error",
    "message": "Item not found."
}
```

If the code of the exception ($exc->getCode()) falls in the range of HTTP status codes, it is used both in the HTTP response header and the response body ("code": 404). For all other exception codes, both the HTTP response status code and the code in the response body will be 400.

This is great for simple tasks, however one may need to provide the client with a more detailed error status codes than the ones defined in the HTTP spec. Consider the following:

`/books/157?user_id=12&access_token=XXX`
The request may fail because the user of ID 12 does not exist, the user 12 is not allowed to see this resource, the access_token is invalid or the book of this ID does not exist, etc.
The client app may need to act differently based on the exact error encountered. However having only the HTTP status codes available, it may lack a unique machine-readable identifier to act upon.

May I propose to either leave the "code" in the response body to always match the $exc->getCode():
```php
throw new Exception('My error.', 12345); // will send a HTTP 400 containing {"code": 12345 ... }
```

Or maybe addind a way to modify data in the response generated by the `ResourcePresenter::sendErrorResource()` method.
This may be as simple as providing a `ResourcePresenter::createErrorResource($exc)` method which converts the exception to the resource and could be overriden easily by extendning the ResourcePresenter.
Or by providing an ErrorResourceFactory which would take care of the exception to resource conversion and would be easy to replace by a custom implementation.

In case you are willing to accept any of the modifications proposed, I would be happy to prepare a pull request.

**Comment by drahak** [comment]
I quite like the error resource factory idea. I've just added this method to resource presenter and I've removed constraint for error code in resource because it was useless. In ErrorResponse the constraint on HTTP response code remains.
