### ISSUE TITLE
Returning 404 Not found is not possible

### ISSUE THREAD

**Issue by MartinMystikJonas** [drahak/Restful#56]
How can I send 404 from actionRead in case resource with given Id does not exists?

Currently I thow `BadRequestException` with 404 code. But it does not works. Respons returned has error message "Method not supported".

Reason is probably this piece of code in `MethodHandler`:
```PHP
public function error(Application $application, \Exception $e)
	{
		if ($e instanceof NetteBadRequestException && $e->getCode() === 404) {
			$this->checkAllowedMethods();
		}
	}
```

Is it error or should i return 404 in different way?

**Comment by MartinMystikJonas** [comment]
Found solution myself :-)

I just leave it here in case somebody else needs info. Maybe you should consider put it in docs.

Instead of:
```php
throw BadRequestexcption::notFound("Not found")
```

use:
```php
  $this->sendErrorResource(BadRequestexcption::notFound("Not found"));
```

**Comment by drahak** [comment]
This was confusing so I've added condition which should resolve it. It throws 405 only if the BadRequestException is raised due to missing route. It's now possible to just throw the exception.
