### ISSUE TITLE
How to add response HTTP header (for CORS)

### ISSUE THREAD

**Issue by deel77** [drahak/Restful#67]
I would like to ask, if there is some easy way for me to specify custom HTTP header with response. I would like to allow cross origin requests (CORS), but I am not so good with nette or PHP. I have found a way to add headers if I have HttpResponse object, but don't know how to access it. Could you point me to some solution?
This is part from my code:
```php
$this->resource->data = $this->database->query("SELECT .........")->fetchAll();
$this->sendResource(IResource::JSON);
```

**Comment by drahak** [comment]
You can get HttpResponse in presenter by calling `getHttpResponse` method: http://api.nette.org/2.3.0/Nette.Application.UI.Presenter.html#_getHttpResponse

``
$this->getHttpResponse()->setHeader('name', 'value');
``

**Comment by deel77** [comment]
Thanks, I overlooked that you are inheriting it all the way up to UI.Presenter. My bad. Still thanks for quick response :+1:
