### ISSUE TITLE
Nette\Framework Not Found

### ISSUE THREAD

**Issue by queejie** [drahak/Restful#78]
I had to change these lines:
		$input = Nette\Framework::VERSION_ID >= 20200 ? // Nette 2.2.0 and/or newer
			$this->httpRequest->getRawBody() :
			file_get_contents('php://input');
to this:
		$input = file_get_contents('php://input');

I don't know enough about Nette or Restful yet to know if this is a real issue, or something with my setup.

**Comment by wodCZ** [comment]
It is already commented in #74, https://github.com/drahak/Restful/pull/74#commitcomment-13590069 but the issue is real.
As a workaround you can add `"nette/nette": "~2.3.0",` to your projects composer.json require section.

**Comment by queejie** [comment]
Thanks!
